#! /bin/sh
# deplace nom_de_fichier rep1 rep2

# verification de la presence de 3 parametres et seulement 3
if [ $# -ne 3 ]; then
   echo "Utilisation : $0 nom_de_fichier repertoire1 repertoire2">&2
   exit 1
fi
if ! test -d "$2" ; then
   echo "$2 n'est pas un repertoire !" >&2
   exit 2
fi
if ! test -d "$3" ; then
   echo "$3 n'est pas un repertoire !" >&2
   exit 3
fi
if test -f "$2/$1" ; then
   if test -f "$3/$1" ; then
      echo "$1 est dans $2 ET dans $3 ! Abandon !" >&2
      exit 5
   else
      mv "$2/$1" "$3"
   fi
else
   if test -f "$3/$1" ; then
      mv "$3/$1" "$2"
   else
      echo "$1 n'est ni dans $2 ni dans $3 !" >&2
      exit 4
   fi
fi
exit 0  # tout s'est bien passe !!


if ! test -f "$1" ; then
   echo "$1 n'est pas un fichier !" >&2
   exit 2
fi



